### PR TITLE
Closes #595 center the star icon for favorite project

### LINKED ISSUE #595: Center star for project names on sidebar

### PR DESCRIPTION
**Pull request by cyrielo**
# Description
Centers the star, for favorite project

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Impacted Areas in Application
List general components of the application that this PR will affect:

Which pages?

- [x] All Projects Page

Specific components 

* ProjectSelection

# Testing Script:

###Login Page
* Successfully login to the application and get taken to the project page

### All Project Page
* Switch between projects 
* Search for a sample
* Navigate through different pages of samples
* Select Upload new sample button
* Select sample to see generated report

# Checklist:

- [x] I have run through the testing script to make sure current functionality is unchanged
- [x] I have done relevant tests that prove my fix is effective or that my feature works
- [x] I have spent time testing out edge cases for my feature
- [x] I have updated the test script or pull request template if necessary
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by sadelokiki** [comment]
lgtm

**Comment by cdebourcy** [comment]
doesn't look centered to me actually? Now it's below the center line whereas before it was above
screen shot 2018-02-08 at 10 27 43 am

**Comment by eggerdesigns** [comment]
@cyrielo yeah this doesn't look centered - moving this back to TODO

**Comment by yunfangjuan** [comment]
branch name makes it impossible to merge.

**Pull request closed without merging**
