### PR TITLE
Update notification emails

### PR DESCRIPTION
**Pull request by tfrcarvalho**
* Updated email format: add new user to project, add existing user to project and reset password:
* Add email previews from rails

email

### CODE REVIEW

**Comment by jshoe** [comment]
Copy nits: what do you think about "The IDseq Team" (with capital Team), and "Welcome to IDseq!" instead of "Join IDseq!"

Interesting I guess the yarn.lock was supposed to update..

**Comment by tfrcarvalho** [comment]
@jshoe Will add the capital T.
I believe is not "Welcome" until first sign up/in.

Did you mean that `yarn.lock` **wasn't** supposed to update?

**Comment by jshoe** [comment]
@tfrcarvalho I'm fine with that

Ah I think it /was/ supposed to update since it happened in Charles's pr too

**Comment by tfrcarvalho** [comment]
@tfrcarvalho But it did update!

**Pull request merged**
