### PR TITLE
Add fix script for count reads bug

### PR DESCRIPTION
**Pull request by jshoe**
- Tested on some staging samples to do what it's supposed to
- Single end case seems to have run_cdhitdup.reads_before as 3x of run_priceseqfilter.reads_after
- For the non-paired files: Ran with == "3" instead of "1.5" for the comparison but /= 1.5 for the operation still to be faithful to the previous version.

- Confirmed affected samples started on 6/5 with
```
pipeline_runs = PipelineRun.where("created_at > ?", 30.days.ago)
pipeline_runs.each do |pr|
  stats = pr.job_stats
  if stats.find_by("task": "run_cdhitdup")
    if stats.find_by("task": "run_cdhitdup").reads_before > stats.find_by("task": "run_priceseqfilter").reads_after && (stats.find_by("task": "run_cdhitdup").reads_before == 1.5 * stats.find_by("task": "run_priceseqfilter").reads_after)
      puts "affected " + pr.created_at.to_s
    else
      puts "not affected"
    end
  end
end
```

### CODE REVIEW

**Comment by jshoe** [comment]
Affected pipeline run IDs:
7404
7405
7406
7407
7408
7409
7410
7411
7412
7413
7414
7415
7416
7417
7418
7419
7420
7421
7422
7423
7424
7425
7426
7427
7428
7429
7430
7433
7434
7435
7436
7438
7439
7440
7441
7442
7443
7444
7448
7449
7457
7458
7459
7462
7463
7465
7467
7472
7475
7476
7477
7478
7479
7480
7481
7482
7483
7484
7485
7486
7487
7488
7489
7490
7491
7492
7493
7494
7495
7496
7497
7498
7500
7501
7502
7503
7504
7505
7506
7507
7508
7509
7510
7511
7512
7513
7514
7515
7516
7517
7518
7519
7520
7521
7522
7523
7524
7525
7526
7527
7528
7529
7530
7531
7532
7533
7534
7535
7536
7537
7538
7539
7540
7541
7542
7543
7544
7545
7546
7547
7548
7549
7550
7551
7552
7553
7554
7555
7556
7557
7558
7559
7560
7561
7562
7563
7564
7565
7566
7567
7568
7569
7570
7571
7572
7574
7576
7578
7579
7580
7584
7586
7587
7589
7591
7592
7613
7620
7637
7639
7640
7641
7642
7643
7644
7645
7646
7647
7652
7654
7655
7656
7657
7658
7659
7660
7661
7662
7663
7664
7665
7666
7667
7668
7669
7670
7671
7672
7673
7674
7675
7676
7677
7678
7679
7680
7681
7614 (single)
7648 (single)
7649 (single)
7650 (single)
7651 (single)

**Comment by tfrcarvalho** [comment]
Do we need to run this ever again?

**Comment by jshoe** [comment]
@tfrcarvalho probably not but we've been trying to document the one-offs :p either in a rake task or closed issue

**Comment by tfrcarvalho** [comment]
OK, I would suggest:
- a header on top of the file with a description of the issue and fix
- placing these type of tasks in their own folder (e.g. lib/tasks/fixes or something similar)

**Pull request closed without merging**
