### PR TITLE
Update css-loader to version ^3.4.2 (IDSEQ-2216)

### PR DESCRIPTION
**Pull request by lvreynoso**
# Description

This PR updates css-loader to the newest version. Breaking changes in config were introduced, so some webpack configuration has been updated for the latest version.

# Notes

The `minimize` option for css-loader was deprecated; this has been replaced by adding `postcss-loader` to the webpack build, with the `cssnano` plugin option.

# Tests

* Run `npm start` to ensure webpack builds correctly
* Navigate around all of idseq to ensure CSS is working properly

### CODE REVIEW

**Comment by jshoe** [comment]
Are you able to tell / test that the CSS is still getting minified? :)

**Comment by lvreynoso** [comment]
Yes, I made sure to check :)

without cssnano:

Screen Shot 2020-02-18 at 4 44 41 PM

with cssnano:

Screen Shot 2020-02-18 at 4 44 22 PM

**Comment by tfrcarvalho** [comment]
@lvreynoso Do you know why the JS size went down?
Actually these numbers seem inflated... are these dev ?

**Comment by lvreynoso** [comment]
I don't know why the JS size went down, I only touched the webpack config. I believe this is dev, yes.

**Pull request merged**
