### PR TITLE
Make style tweaks to report page top filters

### PR DESCRIPTION
**Pull request by jshoe**
- So I managed to swap out the "name type" and "background model" dropdowns for Semantic UI dropdowns since that was straightforward.
- The search box, category box, and advanced filters box had a lot of custom JS/HTML so I didn't want to change all of that right now for the sake of time, so I just standardized CSS tweaks for those.
- So all of the JS hooks and actions should be the same / functionally the same as before basically.
- Might not fix all the visual bugs people mentioned but good enough to get out now.

PART ONE:
part 1

PART TWO:
part 2

### CODE REVIEW

**Comment by yunfangjuan** [comment]
Hi,
I tested the branch. It looks a lot better. A few comments. 
1. When you have multiple advanced filters, the save button will be pushed out of the modal, which is not desirable. 
2.  when the advanced filters wrapped, it's not aligned with other drop downs. 
3. The "Categories" and "Advanced Filters" text are not vertically centered in the dropdown.

**Comment by jshoe** [comment]
@yunfangjuan Okay I made those 3 changes!

part 3 3

**Comment by yunfangjuan** [comment]
awesome let me check

**Comment by jshoe** [comment]
@eggerdesigns advanced filters look a little better now

screen shot 2018-03-14 at 2 27 13 pm

**Comment by jshoe** [comment]
Also fixes "cloud download alternate" references now. Semantic UI React calls the icon 'cloud download' but Semantic UI regular calls it 'cloud download alternate'

**Pull request merged**
