### PR TITLE
fix genome selection

### PR DESCRIPTION
**Pull request by cyrielo**
This PR fixes the genus selection bug in the sample create form

### CODE REVIEW

**Comment by sadelokiki** [comment]
Thanks! Please change initial value of this.state.hostName to this.state.host

**Comment by yunfangjuan** [comment]
I just checked out the branch and it's not working if you test on samples/new

**Comment by cdebourcy** [comment]
same here

**Comment by cyrielo** [comment]
You're right @yunfangjuan, it would need to send the updated host id. @sadelokiki would look into it to update the PR

**Comment by yunfangjuan** [comment]
i have a fix for this. you can close the pr now. I will submit it shortly.

**Pull request closed without merging**
