### PR TITLE
Update the RFP banner on master

### PR DESCRIPTION
**Pull request by jshoe**

### CODE REVIEW

**Comment by jshoe** [comment]
The RFP closes on Dec 5, 2018, but I don't think the current frequency of updating the banner requires putting in start date/end date logic. (And in the other direction adding more bulletins would require more styling changes)

**Comment by tfrcarvalho** [comment]
@jshoe But should we state the data explicitly in the banner?

**Comment by jshoe** [comment]
Oh sorry, is that what you meant.. I can add that @tfrcarvalho

**Comment by cdebourcy** [comment]
Just trying to avoid a situation in which we forget about the landing page / banner and then end up with stale announcements. Would be easy to add an end date in rails, just like we added a start date

**Comment by jshoe** [comment]
Ok, I'll add that stuff back in then @cdebourcy

**Pull request merged**
