### PR TITLE
Improve basespace uploading logic.

### PR DESCRIPTION
**Pull request by MarkAZhang**
# Description

Different approach that uses curl and streaming to remove the need for storing the file in disk on the resque worker.

# Notes

Also added a new function in Syscall that wraps around the shell commands to make testing easier. Renamed the existing `pipe` method in `Syscall` to `pipe_with_output` to distinguish it from the new pipe.

# Tests
* Verify that Basespace uploading still works.
* Verify that tests pass.
* On staging, will verify that the samples still run through the entire pipeline correctly (and all results are loaded).

### CODE REVIEW

**Comment by jshoe** [comment]
looks correct to me 👍

**Comment by cdebourcy** [comment]
> Does it do the same input truncation that the S3 to S3 upload does?

https://github.com/chanzuckerberg/idseq-web/blob/4374e56f41ec13d92cc6a58e6193267a5c3b92c4/app/models/sample.rb#L287

**Comment by MarkAZhang** [comment]
@cdebourcy It does not do the truncation. I think we discussed at some point that since the validate_input dag step also does the truncation, doing it here seems redundant. Unzipping, truncating, and then re-zipping can take a significant amount of time. It does mean uploading a smaller file, but overall it might actually take more time. Let me know if you think the truncation is worth it.

**Comment by tfrcarvalho** [comment]
> Let me know if you think the truncation is worth it.

Is there any limit in file size? We should not be exposed to files that are extremely large. Even if we accept basespace limit we are letting another company do that restriction for us.

**Comment by davidrissato** [comment]
I don't think truncation should happen here. If we do not agree with the file size, we should reject when the user is selecting it.

**Comment by MarkAZhang** [comment]
Ready to be looked at. I will do the file size restriction in a separate PR. The restriction code is unrelated to the upload code in this PR.

**Pull request merged**
