### PR TITLE
add alignment length to heatmap filters

### PR DESCRIPTION
**Pull request by cdebourcy**
Requested by Emily

### CODE REVIEW

**Comment by happyimadesignr** [comment]
@cdebourcy did you add something that affects the interface? Can you send screenshot?

**Comment by cdebourcy** [comment]
@happyimadesignr 
image

**Comment by cdebourcy** [comment]
@happyimadesignr see above -- any thoughts? (As discussed in the channel, I added this because it was a P0 blocking pipeline problem for Emily/Vida that led them to see wrong results)

**Comment by happyimadesignr** [comment]
Awesome, thanks @cdebourcy!

**Pull request merged**
